[package]
name = "rndr-phys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rndr-math = { path = "../rndr-math" }
rndr-core = { path = "../rndr-core" }
